namespace UsageMonitorWpf.Core;

// Korean/English string table.
// - XAML reads keys as {DynamicResource key}; Apply() pushes them into Application resources.
// - Code uses T(key, args). Messages kept in state use Msg(key, args) and are resolved by Display() at render
//   time, so switching language also re-translates messages that were produced earlier.
public static class Loc
{
    private const char Sep = '\u001f';

    private static readonly Dictionary<string, (string En, string Ko)> Strings = new()
    {
        // Window / header
        ["ui.appName"] = ("Usage Monitor", "AI 사용량 모니터"),
        ["ui.refreshing"] = ("Refreshing…", "갱신 중…"),
        ["ui.refresh"] = ("Refresh", "새로고침"),
        ["ui.saveSnapshot"] = ("Save Snapshot", "스냅샷 저장"),
        // Left column
        ["ui.liveChips"] = ("Live Chips", "라이브 칩"),
        ["ui.liveChipsDesc"] = ("Also docked above the taskbar", "작업표시줄 바로 위에도 표시됩니다"),
        ["ui.miniWidget"] = ("Mini Widget", "미니 위젯"),
        ["ui.nextReset"] = ("Next reset", "다음 리셋"),
        ["ui.5h"] = ("5H", "5시간"),
        ["ui.5hour"] = ("5 Hour", "5시간"),
        ["ui.weekly"] = ("Weekly", "주간"),
        ["ui.monthly"] = ("Monthly", "월간"),
        ["ui.collectionLevel"] = ("Collection level", "수집 레벨"),
        // Tabs
        ["ui.tab.overview"] = ("Overview", "개요"),
        ["ui.tab.history"] = ("History", "기록"),
        ["ui.tab.accounts"] = ("Accounts", "계정"),
        ["ui.tab.snapshot"] = ("Snapshot", "스냅샷"),
        ["ui.tab.diagnostics"] = ("Diagnostics", "진단"),
        ["ui.tab.settings"] = ("Settings", "설정"),
        // Overview
        ["ui.controlCenter"] = ("Control Center", "컨트롤 센터"),
        ["ui.controlCenterDesc"] = ("Usage, reset windows, where each value came from, and provider health.", "사용량, 리셋 주기, 각 값의 출처, Provider 상태를 한눈에 봅니다."),
        ["ui.velocity"] = ("Usage velocity", "사용 속도"),
        ["ui.forecast"] = ("Limit forecast", "한도 도달 예측"),
        ["ui.fieldSources"] = ("Field sources", "필드별 출처"),
        // History
        ["ui.usageHistory"] = ("Usage History", "사용량 기록"),
        ["ui.usageHistoryDesc"] = ("5H usage per account (Copilot: monthly), stored locally for 30 days.", "계정별 5시간 사용량(Copilot은 월간)을 로컬에 30일간 보관합니다."),
        ["ui.weeklyUsageHistory"] = ("Weekly usage", "주간 사용량 기록"),
        ["ui.weeklyUsageHistoryDesc"] = ("Weekly usage per account against its own reset cycle.", "계정별 주간 사용량을 리셋 주기 대비로 보여줍니다."),
        ["ui.resetTimeline"] = ("Reset timeline (current window)", "리셋 타임라인 (현재 윈도우)"),
        ["ui.resetHistory"] = ("Reset history (7 days)", "리셋 기록 (최근 7일)"),
        // Accounts
        ["ui.accounts"] = ("Accounts", "계정"),
        ["ui.accountsDesc"] = ("Monitor several Claude Code / Codex logins at once. Each extra account points at its own CLI config folder (CLAUDE_CONFIG_DIR / CODEX_HOME).",
            "여러 Claude Code / Codex 로그인을 동시에 모니터링합니다. 추가 계정은 각자의 CLI 설정 폴더(CLAUDE_CONFIG_DIR / CODEX_HOME)를 지정합니다."),
        ["ui.comparison"] = ("Comparison", "계정 비교"),
        ["ui.col.account"] = ("Account", "계정"),
        ["ui.col.source"] = ("Source", "출처"),
        ["ui.col.health"] = ("Health", "상태"),
        ["ui.manage"] = ("Manage", "관리"),
        ["ui.enabled"] = ("Enabled", "사용"),
        ["ui.configDirTip"] = ("Config folder (empty = default ~/.claude or ~/.codex)", "설정 폴더 (비우면 기본값 ~/.claude 또는 ~/.codex)"),
        ["ui.remove"] = ("Remove", "삭제"),
        ["ui.applyChanges"] = ("Apply changes", "변경 적용"),
        ["ui.addAccount"] = ("Add account", "계정 추가"),
        ["ui.add"] = ("Add", "추가"),
        ["ui.addAccountDesc"] = ("Provider · account name · config folder. Log in to that folder first, e.g. set CLAUDE_CONFIG_DIR / CODEX_HOME and run the CLI login.",
            "Provider · 계정 이름 · 설정 폴더 순서입니다. 먼저 그 폴더로 로그인해 두세요 (예: CLAUDE_CONFIG_DIR / CODEX_HOME 지정 후 CLI 로그인)."),
        // Snapshot
        ["ui.manualSnapshot"] = ("Manual Snapshot", "수동 스냅샷"),
        ["ui.manualSnapshotDesc"] = ("Type values by hand (Safe level, or when live collectors fail). Live collectors overwrite manual values on the next refresh.",
            "값을 직접 입력합니다 (Safe 레벨이거나 자동 수집이 실패할 때). 자동 수집이 성공하면 다음 갱신 때 수동 값을 덮어씁니다."),
        ["ui.plan"] = ("Plan", "플랜"),
        ["ui.source"] = ("Source", "출처"),
        ["ui.5hUsage"] = ("5H usage %", "5시간 사용률 %"),
        ["ui.weeklyUsage"] = ("Weekly usage %", "주간 사용률 %"),
        ["ui.monthlyUsage"] = ("Monthly usage %", "월간 사용률 %"),
        ["ui.5hReset"] = ("5H reset", "5시간 리셋"),
        ["ui.weeklyReset"] = ("Weekly reset", "주간 리셋"),
        ["ui.monthlyReset"] = ("Monthly reset", "월간 리셋"),
        ["ui.confidence"] = ("Confidence", "신뢰도"),
        ["ui.saveManualSnapshot"] = ("Save manual snapshot", "수동 스냅샷 저장"),
        // Diagnostics
        ["ui.collectorDiagnostics"] = ("Collector Diagnostics", "Collector 진단"),
        // Settings
        ["ui.settings"] = ("Settings", "설정"),
        ["ui.settingsDesc"] = ("No backend, no telemetry, no API keys, credentials stay local. Only token-free collectors allowed by the collection level run automatically.",
            "백엔드·텔레메트리·API 키 없음. 인증 정보는 로컬에만 머뭅니다. 수집 레벨이 허용한 비과금(token-free) Collector만 자동 실행됩니다."),
        ["ui.refreshInterval"] = ("Refresh interval", "갱신 주기"),
        ["ui.favorite"] = ("Favorite (primary) provider", "기본(주) Provider"),
        ["ui.widgetMode"] = ("Widget mode", "위젯 모드"),
        ["ui.windowVersion"] = ("Window version", "창 모드"),
        ["ui.displayUsageAs"] = ("Display usage as", "사용량 표시 방식"),
        ["ui.language"] = ("Language", "언어"),
        ["ui.theme"] = ("Color theme", "테마"),
        ["ui.customThemeDesc"] = ("Custom accepts WPF color values such as #RRGGBB or #AARRGGBB.", "Custom은 #RRGGBB 또는 #AARRGGBB 형식의 색상 값을 사용할 수 있습니다."),
        ["ui.customInk"] = ("Text", "글자"),
        ["ui.customMuted"] = ("Muted text", "보조 글자"),
        ["ui.customAccent"] = ("Accent", "포인트"),
        ["ui.customPanel"] = ("Panel", "패널"),
        ["ui.customCanvas"] = ("Canvas", "배경"),
        ["ui.customLine"] = ("Line", "선"),
        ["ui.customHeader"] = ("Header text", "헤더 글자"),
        ["ui.customHeaderStart"] = ("Header start", "헤더 시작"),
        ["ui.customHeaderMiddle"] = ("Header middle", "헤더 중간"),
        ["ui.customHeaderEnd"] = ("Header end", "헤더 끝"),
        ["ui.customColors"] = ("Custom colors", "사용자 색"),
        ["ui.addCustomColor"] = ("+ Add", "+ 추가"),
        ["ui.resetCustomTheme"] = ("Reset to default", "기본값으로 되돌리기"),
        ["ui.presets"] = ("Presets", "프리셋"),
        ["ui.presetNamePlaceholder"] = ("Preset name", "프리셋 이름"),
        ["ui.savePreset"] = ("Save", "저장"),
        ["ui.applyPreset"] = ("Apply", "적용"),
        ["ui.deletePreset"] = ("Delete", "삭제"),
        ["ui.notifications"] = ("Threshold notifications", "임계치 알림"),
        ["ui.thresholds"] = ("Thresholds (%)", "알림 임계치 (%)"),
        ["ui.thresholdsTip"] = ("Comma separated, e.g. 70, 80, 90, 95, 100", "쉼표로 구분, 예: 70, 80, 90, 95, 100"),
        ["ui.taskbarChips"] = ("Taskbar chips", "작업표시줄 칩"),
        ["ui.alwaysOnTop"] = ("Mini widget always on top", "미니 위젯 항상 위"),
        ["ui.widgetOpacity"] = ("Mini widget opacity", "미니 위젯 투명도"),
        ["ui.chipsOpacity"] = ("Taskbar chips opacity", "작업표시줄 칩 투명도"),
        ["ui.hoverOpaque"] = ("Opaque on mouse hover", "마우스를 올리면 불투명"),
        ["ui.internalVersion"] = ("Internal version", "내부 버전"),
        ["ui.stateSchema"] = ("State schema", "상태 스키마"),
        ["ui.about"] = ("About", "정보"),
        ["ui.appLegalName"] = ("AI Usage Monitor", "AI Usage Monitor"),
        ["ui.aboutDesc"] = ("AI Coding Usage Monitor", "AI 코딩 사용량 모니터"),
        ["ui.copyright"] = ("Copyright © 2026 leedoha0403", "Copyright © 2026 leedoha0403"),
        ["ui.licenseSummary"] = ("Free for personal and internal business use. Commercial resale and redistribution are prohibited.",
            "개인 사용과 회사/학교/조직 내부 업무용 사용은 무료입니다. 상업적 재판매 및 재배포는 금지됩니다."),
        ["ui.disclaimer"] = ("Independent project. Not affiliated with, endorsed by, or sponsored by OpenAI or Anthropic.",
            "독립적으로 개발된 프로젝트이며 OpenAI 또는 Anthropic과 제휴, 후원, 승인 관계가 아닙니다."),
        ["ui.trademarkNotice"] = ("OpenAI, ChatGPT, Codex, Anthropic, Claude, and related names and trademarks are the property of their respective owners.",
            "OpenAI, ChatGPT, Codex, Anthropic, Claude 및 관련 명칭과 상표는 각 권리자의 소유입니다."),
        ["ui.licenses"] = ("Licenses", "라이선스"),
        ["ui.license"] = ("License", "라이선스"),
        ["ui.openSourceLicenses"] = ("Open Source Licenses", "오픈소스 라이선스"),
        ["ui.githubRepository"] = ("GitHub Repository", "GitHub 저장소"),
        ["ui.reportIssue"] = ("Report Issue", "이슈 제보"),
        ["ui.checkForUpdate"] = ("Check for updates", "업데이트 확인"),
        ["ui.checkingUpdate"] = ("Checking…", "확인 중…"),
        ["ui.upToDate"] = ("You're up to date.", "최신 버전입니다."),
        ["ui.updateCheckFailed"] = ("Couldn't check for updates.", "업데이트 확인에 실패했습니다."),
        ["ui.updateAvailable"] = ("Update available: {0}", "새 버전 사용 가능: {0}"),
        ["ui.downloadUpdate"] = ("Download", "다운로드"),
        ["ui.downloadingUpdate"] = ("Downloading… {0}%", "다운로드 중… {0}%"),
        ["ui.updateDownloaded"] = ("Downloaded. Close the app, unzip, and replace the exe.", "다운로드 완료. 앱을 종료하고 압축을 풀어 exe를 교체하세요."),
        ["ui.updateDownloadFailed"] = ("Download failed: {0}", "다운로드 실패: {0}"),
        ["ui.updateChecksumFailed"] = ("Downloaded file failed checksum verification and was deleted.", "다운로드한 파일이 체크섬 검증에 실패해 삭제했습니다."),
        ["ui.updateNoAsset"] = ("This release has no downloadable build for this platform.", "이 릴리스에는 이 플랫폼용 배포 파일이 없습니다."),
        ["ui.releaseNotes"] = ("Release Notes", "릴리스 노트"),
        ["ui.close"] = ("Close", "닫기"),
        ["ui.licenseDialogDesc"] = ("Full project license terms bundled with this app.", "앱에 포함된 프로젝트 라이선스 전문입니다."),
        ["ui.thirdPartyDialogDesc"] = ("Third-party components and license notices bundled with this app.", "앱에 포함된 외부 구성 요소와 라이선스 고지입니다."),
        ["ui.legalFileMissing"] = ("Could not find {0} in the app folder.", "앱 폴더에서 {0} 파일을 찾을 수 없습니다."),
        ["ui.dataDirectory"] = ("Data directory: ", "데이터 폴더: "),
        // Widget / chips / tray
        ["ui.aiUsage"] = ("AI Usage", "AI 사용량"),
        ["ui.details"] = ("Details", "상세"),
        ["ui.hide"] = ("Hide", "숨기기"),
        ["ui.opacity"] = ("Opacity", "투명도"),
        ["ui.openDashboard"] = ("Open Dashboard", "대시보드 열기"),
        ["ui.openWidget"] = ("Open Widget", "위젯 열기"),
        ["ui.hideChips"] = ("Hide Chips", "칩 숨기기"),
        ["ui.showChips"] = ("Show Chips", "칩 보이기"),
        ["ui.showWidget"] = ("Show Widget", "위젯 보이기"),
        ["ui.exit"] = ("Exit", "종료"),
        ["ui.on"] = ("On", "켜기"),
        ["ui.off"] = ("Off", "끄기"),
        ["ui.resetsIn"] = ("Resets in", "리셋까지"),

        // Option labels
        ["opt.Compact"] = ("Compact", "간단히"),
        ["opt.Normal"] = ("Normal", "보통"),
        ["opt.Detailed"] = ("Detailed", "자세히"),
        ["opt.Mini"] = ("Mini", "미니"),
        ["opt.Expanded"] = ("Expanded", "확장"),
        ["opt.System"] = ("System", "시스템 설정"),
        ["opt.Light"] = ("Light", "라이트"),
        ["opt.Dark"] = ("Dark", "다크"),
        ["opt.Custom"] = ("Custom", "Custom"),
        ["opt.Remaining"] = ("Remaining", "남은 양"),
        ["opt.Used"] = ("Used", "사용한 양"),
        ["opt.Combined"] = ("Combined", "함께 보기"),
        ["opt.Session"] = ("5H only", "시간당만"),
        ["opt.Weekly"] = ("Weekly only", "주간만"),
        ["opt.Safe"] = ("Safe", "Safe (로컬만)"),
        ["opt.Standard"] = ("Standard", "Standard (공식 조회)"),
        ["opt.Deep"] = ("Deep", "Deep (확장 탐색)"),
        ["opt.Korean"] = ("한국어", "한국어"),
        ["opt.English"] = ("English", "English"),
        ["opt.1H"] = ("1H", "1시간"),
        ["opt.6H"] = ("6H", "6시간"),
        ["opt.1D"] = ("1D", "1일"),
        ["opt.7D"] = ("7D", "7일"),
        ["opt.30D"] = ("30D", "30일"),
        ["opt.claude"] = ("Claude Code", "Claude Code"),
        ["opt.codex"] = ("Codex", "Codex"),
        ["opt.refresh.0"] = ("Off", "끔"),
        ["opt.refresh.sec"] = ("{0} sec", "{0}초"),
        ["opt.refresh.min"] = ("{0} min", "{0}분"),

        // Sources / confidence / health
        ["src.Official"] = ("Official", "공식"),
        ["src.SessionLog"] = ("Session log", "세션 로그"),
        ["src.Local Cache"] = ("Local cache", "로컬 캐시"),
        ["src.Local"] = ("Local", "로컬"),
        ["src.Manual"] = ("Manual", "수동"),
        ["src.RateLimit"] = ("Rate-limit header", "Rate-limit 헤더"),
        ["conf.High"] = ("High", "높음"),
        ["conf.Medium"] = ("Medium", "보통"),
        ["conf.Low"] = ("Low", "낮음"),
        ["health.READY"] = ("Healthy", "정상"),
        ["health.LOCAL"] = ("Local only", "로컬 전용"),
        ["health.NOT_SIGNED_IN"] = ("Not signed in", "로그인 필요"),
        ["health.DEGRADED"] = ("Degraded", "수집 실패"),

        // Provider view
        ["pv.notSignedIn"] = ("Not signed in", "로그인 필요"),
        ["pv.used"] = ("{0}% used", "{0}% 사용"),
        ["pv.left"] = ("{0}% left", "{0}% 남음"),
        ["pv.weekUsed"] = ("Week {0}% used · {1}", "주간 {0}% 사용 · {1}"),
        ["pv.weekLeft"] = ("Week {0}% left · {1}", "주간 {0}% 남음 · {1}"),
        ["pv.monthUsed"] = ("Month {0}% used · {1}", "월간 {0}% 사용 · {1}"),
        ["pv.monthLeft"] = ("Month {0}% left · {1}", "월간 {0}% 남음 · {1}"),
        ["pv.summary"] = ("{0}% remaining · resets in {1}", "{0}% 남음 · {1} 후 리셋"),
        ["pv.resetIn"] = ("Resets in {0}", "리셋까지 {0}"),
        ["pv.summaryState"] = ("{0}% remaining · {1}", "{0}% 남음 · {1}"),
        ["pv.windowStarting"] = ("New window started · checking…", "새 창 시작됨 · 확인 중…"),
        ["pv.windowStartingShort"] = ("checking", "확인 중"),
        ["pv.plan"] = ("Plan: {0}", "플랜: {0}"),
        ["pv.sourceLine"] = ("Source: {0}", "출처: {0}"),
        ["pv.weeklyResetLine"] = ("Weekly reset: {0}", "주간 리셋: {0}"),
        ["pv.monthlyResetLine"] = ("Monthly reset: {0}", "월간 리셋: {0}"),
        ["pv.noForecastMonthly"] = ("Monthly quota: no 5H-window forecast", "월간 한도라 5시간 기준 추정이 없습니다"),
        ["pv.lastSuccess"] = ("Last successful usage check: {0}", "마지막 사용량 조회: {0}"),
        ["pv.extra"] = ("Extra usage (paid): {0}{1} this month", "추가 사용량(유료): 이번 달 {0}{1}"),
        ["pv.credits"] = ("Credits balance: {0}", "크레딧 잔액: {0}"),
        ["pv.health"] = ("{0} · via {1}{2}{3}", "{0} · {1} 사용{2}{3}"),
        ["pv.failures"] = (" · {0} failed refresh(es)", " · 연속 실패 {0}회"),
        ["pv.none"] = ("none", "없음"),
        ["pv.field.session"] = ("5H usage", "5시간 사용량"),
        ["pv.field.sessionReset"] = ("5H reset", "5시간 리셋"),
        ["pv.field.weekly"] = ("Weekly usage", "주간 사용량"),
        ["pv.field.weeklyReset"] = ("Weekly reset", "주간 리셋"),
        ["pv.field.monthly"] = ("Monthly usage", "월간 사용량"),
        ["pv.field.monthlyReset"] = ("Monthly reset", "월간 리셋"),
        ["pv.field.plan"] = ("Plan", "플랜"),
        ["pv.noHistory"] = ("Estimated: not enough recent history", "추정: 최근 기록이 부족합니다"),
        ["pv.velocity"] = ("Last 30 min {0}% · {1:0.#}% / hour (estimated)", "최근 30분 {0}% · 시간당 {1:0.#}% (추정)"),
        ["pv.signedOutData"] = ("No data while signed out", "로그인 전에는 데이터가 없습니다"),
        ["pv.noResets"] = ("No completed windows recorded in the last 7 days", "최근 7일간 완료된 윈도우 기록이 없습니다"),
        ["pv.resetSummary"] = ("{0} window(s) in 7 days · limit reached {1} time(s)", "7일간 윈도우 {0}개 · 한도 도달 {1}회"),
        ["pv.peak"] = ("peak", "최대"),

        // Analytics
        ["an.limitReached"] = ("Limit reached · resets in {0}", "한도 도달 · {0} 후 리셋"),
        ["an.limitReachedPending"] = ("Limit reached · reset pending", "한도 도달 · 리셋 대기"),
        ["an.flat"] = ("Estimated: usage flat, limit not expected this window", "추정: 사용량 변화 없음, 이번 윈도우에서 한도 도달 예상 없음"),
        ["an.limitIn"] = ("Estimated: 5H limit in {0} (~{1})", "추정: {0} 후 5시간 한도 도달 (~{1})"),
        ["an.resetsFirst"] = ("Estimated: window resets before the limit (~{0}% at reset)", "추정: 한도 전에 리셋됨 (리셋 시점 ~{0}%)"),
        ["an.windowStarted"] = ("Window started", "윈도우 시작"),
        ["an.resetIn"] = ("Reset (in {0})", "리셋 ({0} 후)"),
        ["an.reset"] = ("Reset", "리셋"),
        ["an.limit"] = ("LIMIT", "한도"),

        // Formatters
        ["fmt.resetPending"] = ("Reset pending", "리셋 대기"),
        ["fmt.resetSoon"] = ("Reset soon", "곧 리셋"),
        ["fmt.attention"] = ("Attention", "주의"),
        ["fmt.normal"] = ("Normal", "여유"),
        ["fmt.never"] = ("never", "없음"),
        ["fmt.secAgo"] = ("{0}s ago", "{0}초 전"),
        ["fmt.minAgo"] = ("{0}m ago", "{0}분 전"),
        ["fmt.hourAgo"] = ("{0}h {1}m ago", "{0}시간 {1}분 전"),
        ["fmt.dayAgo"] = ("{0}d ago", "{0}일 전"),
        ["fmt.lt1m"] = ("<1m", "1분 미만"),
        ["fmt.min"] = ("{0}m", "{0}분"),
        ["fmt.hourMin"] = ("{0}h {1:00}m", "{0}시간 {1:00}분"),
        ["fmt.dayHour"] = ("{0}d {1}h", "{0}일 {1}시간"),

        // Aggregator / collectors (stored as Msg keys)
        ["msg.waiting"] = ("Waiting for first snapshot", "첫 스냅샷 대기 중"),
        ["msg.manualSaved"] = ("Manual snapshot saved", "수동 스냅샷 저장됨"),
        ["msg.live"] = ("Live data from {0}", "{0} 출처의 실시간 데이터"),
        ["msg.safeOnly"] = ("Safe level: local cache/manual snapshot only", "Safe 레벨: 로컬 캐시/수동 스냅샷만 사용"),
        ["msg.notSignedIn"] = ("Not signed in. {0}", "로그인이 필요합니다. {0}"),
        ["msg.degraded"] = ("Live collectors failed; showing last known values", "자동 수집 실패 · 마지막 값을 표시합니다"),
        ["msg.disabledUnverified"] = ("Disabled: not verified as token-free", "비활성: 비과금(token-free) 검증 안 됨"),
        ["msg.disabledLevel"] = ("Disabled at {0} level (needs {1})", "{0} 레벨에서는 비활성 ({1} 이상 필요)"),
        ["msg.localCache"] = ("Local cache/manual snapshot", "로컬 캐시/수동 스냅샷"),
        ["msg.localEstimate"] = ("Local estimate (window reset since last update)", "로컬 추정 (마지막 갱신 이후 윈도우 리셋됨)"),
        ["msg.official"] = ("Official usage endpoint", "공식 사용량 엔드포인트"),
        ["msg.noWindows"] = ("Usage endpoint returned no rate-limit windows", "사용량 엔드포인트에 한도 정보가 없습니다"),
        ["msg.httpError"] = ("Usage endpoint returned HTTP {0}", "사용량 엔드포인트 오류 (HTTP {0})"),
        ["msg.readCredFail"] = ("Could not read {0} credentials", "{0} 로그인 정보를 읽을 수 없습니다"),
        ["msg.claudeNoLogin"] = ("Not signed in (no Claude Code CLI login found)", "로그인 필요 (Claude Code CLI 로그인 파일 없음)"),
        ["msg.claudeNoOauth"] = ("Not signed in (credentials file has no OAuth login)", "로그인 필요 (로그인 파일에 OAuth 정보 없음)"),
        ["msg.claudeExpired"] = ("Login expired. Run `claude` once to refresh it.", "로그인이 만료되었습니다. `claude`를 한 번 실행해 갱신하세요."),
        ["msg.claudeRejected"] = ("Login rejected. Run `claude` to sign in again.", "로그인이 거부되었습니다. `claude`로 다시 로그인하세요."),
        ["msg.codexNoLogin"] = ("Not signed in (no Codex CLI login found)", "로그인 필요 (Codex CLI 로그인 파일 없음)"),
        ["msg.codexApiKey"] = ("Codex uses an API key, not a ChatGPT plan login (no 5H/weekly window)", "Codex가 API 키 모드입니다 (ChatGPT 플랜 로그인이 아니라 5시간/주간 한도가 없음)"),
        ["msg.codexRejected"] = ("Login rejected. Run `codex` once to refresh, or `codex login`.", "로그인이 거부되었습니다. `codex`를 실행하거나 `codex login`으로 다시 로그인하세요."),
        ["msg.copilotNoLogin"] = ("Not signed in (no Copilot CLI login found)", "로그인 필요 (Copilot CLI 로그인 없음)"),
        ["msg.copilotNoToken"] = ("No stored Copilot CLI login for {0} in Credential Manager", "자격 증명 관리자에 {0} 계정의 Copilot CLI 로그인이 없습니다"),
        ["msg.copilotRejected"] = ("Login rejected. Run `copilot login` to sign in again.", "로그인이 거부되었습니다. `copilot login`으로 다시 로그인하세요."),
        ["msg.copilotOverage"] = ("Premium requests over quota: {0}", "프리미엄 요청 한도 초과: {0}회"),
        ["msg.noSessions"] = ("No Codex session logs", "Codex 세션 로그 없음"),
        ["msg.noRateLimitEvent"] = ("No rate_limits event in recent Codex sessions", "최근 Codex 세션에 rate_limits 기록 없음"),
        ["msg.sessionLog"] = ("Codex session log ({0})", "Codex 세션 로그 ({0})"),
        ["msg.searched"] = ("Searched: {0}", "탐색 위치: {0}"),
        ["msg.credential"] = ("Credential: {0}", "로그인 정보: {0}"),
        ["msg.lastEvent"] = ("Last rate_limits event {0}", "마지막 rate_limits 기록 {0}"),
        ["msg.rateLimitDisabled"] = ("Disabled: not token-free", "비활성: 사용량을 소모하는 방식"),
        ["vf.claudeOfficial"] = ("GET /api/oauth/usage is a status lookup (no model call). Credentials read locally, sent only to api.anthropic.com, never refreshed or stored.",
            "GET /api/oauth/usage는 상태 조회입니다(모델 호출 아님). 로그인 정보는 로컬에서 읽어 api.anthropic.com으로만 보내며 갱신/저장하지 않습니다."),
        ["vf.codexOfficial"] = ("GET /backend-api/wham/usage is a status lookup (no model call). auth.json read locally, sent only to chatgpt.com, never refreshed or stored.",
            "GET /backend-api/wham/usage는 상태 조회입니다(모델 호출 아님). auth.json은 로컬에서 읽어 chatgpt.com으로만 보내며 갱신/저장하지 않습니다."),
        ["vf.copilotOfficial"] = ("GET /copilot_internal/user is a status lookup (no model call, no premium request). The Copilot CLI login is read locally from Credential Manager, sent only to the GitHub API, never refreshed or stored.",
            "GET /copilot_internal/user는 상태 조회입니다(모델 호출·프리미엄 요청 소모 없음). Copilot CLI 로그인은 자격 증명 관리자에서 로컬로 읽어 GitHub API로만 보내며 갱신/저장하지 않습니다."),
        ["vf.rateLimit"] = ("Requires a Messages API request, which consumes usage. Never run automatically.", "Messages API 호출이 필요해 사용량이 소모됩니다. 자동 실행하지 않습니다."),
        ["vf.sessionLog"] = ("Reads rate_limits events from local ~/.codex/sessions logs. No network access.", "로컬 ~/.codex/sessions 로그의 rate_limits 기록만 읽습니다. 네트워크 사용 안 함."),
        ["vf.local"] = ("Reads only this app's local snapshot cache (state.json)", "이 앱의 로컬 스냅샷 캐시(state.json)만 읽습니다"),
        ["login.banner"] = ("[{0} · {1}] Starting login. Sign in when the browser opens.", "[{0} · {1}] 로그인을 진행합니다. 브라우저가 열리면 로그인하세요."),
        ["login.done"] = ("Done. You can close this window; Usage Monitor detects the login automatically.", "완료되었습니다. 이 창은 닫아도 됩니다. Usage Monitor가 로그인을 자동으로 감지합니다."),
        ["login.installing"] = ("Installing the {0} CLI...", "{0} CLI를 설치합니다..."),
        ["login.installDone"] = ("Install finished. Usage Monitor will open the login window next.", "설치가 끝났습니다. Usage Monitor가 이어서 로그인 창을 엽니다."),
        ["ui.handleTip"] = ("Hover to show the usage widget", "마우스를 올리면 사용량 위젯이 나타납니다"),
        ["ui.fold"] = ("Fold into the screen edge", "화면 가장자리로 접기"),
        ["ui.unfold"] = ("Keep unfolded", "펼친 상태로 고정"),
        ["ui.acc.addClaude"] = ("+ Claude account", "+ Claude 계정"),
        ["ui.acc.addCodex"] = ("+ Codex account", "+ Codex 계정"),
        ["ui.acc.addCopilot"] = ("+ Copilot account", "+ Copilot 계정"),
        ["ui.acc.name"] = ("Account name", "계정 이름"),
        ["ui.acc.folder"] = ("Config folder", "설정 폴더"),
        ["ui.acc.githubLogin"] = ("GitHub login", "GitHub 로그인"),
        ["ui.acc.githubLoginCurrent"] = ("Copilot CLI's current login", "Copilot CLI 현재 로그인"),
        ["ui.acc.githubLoginHint"] = ("Accounts signed in to the Copilot CLI in this folder. Add another with `copilot login`.",
            "이 폴더의 Copilot CLI에 로그인된 계정입니다. 다른 계정은 `copilot login`으로 추가하세요."),
        ["ui.acc.browse"] = ("Browse…", "찾아보기…"),
        ["ui.acc.useDefault"] = ("Use default", "기본값"),
        ["ui.acc.enabled"] = ("Monitor this account", "이 계정 모니터링"),
        ["ui.acc.primary"] = ("Make primary", "기본 계정으로 지정"),
        ["ui.acc.isPrimary"] = ("★ Primary account", "★ 기본 계정"),
        ["ui.acc.loginState"] = ("Login", "로그인"),
        ["ui.acc.relogin"] = ("Log in again", "다시 로그인"),
        ["ui.acc.remove"] = ("Remove account", "계정 삭제"),
        ["ui.acc.defaultNote"] = ("Default accounts cannot be removed; turn monitoring off instead.", "기본 계정은 삭제할 수 없습니다. 대신 모니터링을 끌 수 있습니다."),
        ["ui.acc.viewOverview"] = ("View in overview", "개요에서 보기"),
        ["ui.acc.manage"] = ("Manage account ›", "계정 관리 ›"),
        ["ui.acc.autoSave"] = ("Changes are saved immediately.", "변경 사항은 바로 저장됩니다."),
        ["ui.acc.usage"] = ("Usage", "사용량"),
        ["pv.folderDefault"] = ("Empty = default folder: {0}", "비우면 기본 폴더 사용: {0}"),
        ["pv.loginOk"] = ("Signed in · {0}", "로그인됨 · {0}"),
        ["pv.listStatus"] = ("{0} · {1} {2}%", "{0} · {1} {2}%"),
        ["mv.removeTitle"] = ("Remove account", "계정 삭제"),
        ["mv.removeBody"] = ("Remove '{0}'?\nIts history stays; monitoring stops.", "'{0}' 계정을 삭제할까요?\n기록은 남고 모니터링만 중단됩니다."),
        ["mv.newAccount"] = ("New account {0}", "새 계정 {0}"),
        ["ui.acc.display"] = ("Show in", "표시 위치"),
        ["ui.acc.showMini"] = ("Mini (widget · chips)", "미니 (위젯 · 칩)"),
        ["ui.acc.showDashboard"] = ("Dashboard", "대시보드"),
        ["ui.acc.displayNote"] = ("Hiding only removes it from the screen; the login stays and usage is still collected.", "숨겨도 로그인은 유지되고 사용량도 계속 수집됩니다. 화면에서만 빠집니다."),
        ["ui.acc.monitorOffNote"] = ("Monitoring is off, so this account is neither collected nor shown.", "모니터링이 꺼져 있어 수집도 표시도 하지 않습니다."),
        ["pv.hiddenMini"] = ("mini hidden", "미니 숨김"),
        ["pv.hiddenDashboard"] = ("dashboard hidden", "대시보드 숨김"),
        ["pv.off"] = ("monitoring off", "모니터링 꺼짐"),
        ["ui.runAtStartup"] = ("Start with Windows", "Windows 시작 시 자동 실행"),
        ["ui.runAtStartupNote"] = ("Starts quietly in the tray and chips when you sign in. The dashboard opens from the tray.", "로그인하면 트레이와 칩으로 조용히 시작합니다. 대시보드는 트레이에서 열 수 있습니다."),
        ["ui.runAtStartupStale"] = ("The registered path differs from this app; it is updated automatically at launch.", "등록된 실행 경로가 현재 앱과 달라, 실행 시 자동으로 갱신합니다."),
        ["mv.startupFailed"] = ("Could not change the startup setting: {0}", "자동 실행 설정을 바꾸지 못했습니다: {0}"),
        // ---- Scheduled refresh
        ["ui.tab.refresh"] = ("Refresh", "갱신"),
        ["rf.title"] = ("Scheduled refresh", "예약 갱신"),
        ["rf.subtitle"] = ("Sends one minimal request at the chosen time to start the next usage window.", "지정한 시각에 최소 요청을 보내 다음 사용 주기를 시작합니다."),
        ["rf.costNote"] = ("Scheduled refresh sends one real model request, so it uses a tiny amount of usage. It runs in a new empty session with no tools, no project and no web access.",
            "예약 갱신은 실제 모델 요청을 1회 보내므로 사용량이 아주 조금 소모됩니다. 도구·프로젝트·웹 접근 없이 빈 새 세션에서 실행합니다."),
        ["rf.explain"] = ("Renewable time: when a new window can start.  Notification: tells you it can start.  Scheduled refresh: starts it at that time with a minimal CLI request.",
            "갱신 가능 시각: 언제부터 새 주기를 시작할 수 있는지.  알림: 이제 시작할 수 있다고 알려줌.  예약 갱신: 그 시각에 CLI를 최소 비용으로 자동 호출."),
        ["rf.nextRenew"] = ("Next renewable", "다음 갱신 가능"),
        ["rf.renewableNow"] = ("Renewable now", "지금 갱신 가능"),
        ["rf.notifyOn"] = ("🔔 Alert ON", "🔔 알림 ON"),
        ["rf.notifyOff"] = ("🔔 Alert OFF", "🔔 알림 OFF"),
        ["rf.scheduleButton"] = ("⏱ Schedule", "⏱ 예약 갱신"),
        ["rf.retry"] = ("Try again", "다시 시도"),
        ["rf.change"] = ("Change", "변경"),
        ["rf.cancel"] = ("Cancel", "취소"),
        ["rf.status.Idle"] = ("No schedule", "예약 없음"),
        ["rf.status.Scheduled"] = ("⏱ {0} scheduled", "⏱ {0} 예약됨"),
        ["rf.status.Imminent"] = ("Refresh in {0}", "예약 갱신까지 {0}"),
        ["rf.status.Waiting"] = ("⏱ Moved to {0} (window still active)", "⏱ {0}로 이동 (갱신 가능 대기)"),
        ["rf.status.Running"] = ("↻ Starting a new window…", "↻ 사용 주기 시작 중..."),
        ["rf.status.Success"] = ("✓ New window started {0}", "✓ 새 사용 주기 시작 {0}"),
        ["rf.status.Failed"] = ("⚠ Scheduled refresh failed · {0}", "⚠ 예약 갱신 실패 · {0}"),
        ["rf.status.RetryWaiting"] = ("⚠ Failed · retry at {0} ({1}/{2})", "⚠ 실패 · {0} 재시도 ({1}/{2})"),
        ["rf.status.Missed"] = ("Scheduled time was missed", "예약 시간을 놓쳤습니다"),
        ["rf.status.Blocked"] = ("Login required · schedule on hold", "로그인 필요 · 예약 보류"),
        ["rf.mode.minimal"] = ("Minimal cost", "최소 비용 모드"),
        ["rf.mode.custom"] = ("Custom model: {0}", "사용자 지정 모델: {0}"),
        ["rf.repeat.Once"] = ("once", "한 번만"),
        ["rf.repeat.Every"] = ("every window", "매 갱신 가능 시"),
        ["rf.repeat.Window"] = ("{0}~{1} only", "{0}~{1} 시간대만"),
        ["rf.err.NoCli"] = ("CLI not installed", "CLI 없음"),
        ["rf.err.LoginExpired"] = ("Login expired", "로그인 만료"),
        ["rf.err.ProcessFailed"] = ("Could not start the process", "프로세스 실행 실패"),
        ["rf.err.NoResponse"] = ("No response", "응답 없음"),
        ["rf.err.Network"] = ("Network error", "네트워크 오류"),
        ["rf.err.Canceled"] = ("Canceled", "예약 취소"),
        ["rf.err.Other"] = ("CLI error", "CLI 오류"),
        ["rf.log.postponed"] = ("Window still active; moved to {0}", "아직 갱신 불가 · {0}로 이동"),
        ["rf.log.movedNext"] = ("Missed; moved to {0}", "놓침 · {0}로 이동"),
        ["rf.notify.successTitle"] = ("{0}: new usage window started", "{0}: 새 사용 주기 시작"),
        ["rf.notify.successBody"] = ("Scheduled refresh ran at {0}.", "{0}에 예약 갱신을 실행했습니다."),
        ["rf.notify.failTitle"] = ("{0}: scheduled refresh failed", "{0}: 예약 갱신 실패"),
        ["rf.notify.postponedTitle"] = ("{0}: scheduled refresh postponed", "{0}: 예약 갱신 보류"),
        ["rf.notify.postponedBody"] = ("The current window is still running; it will run at {0}.", "아직 현재 사용 주기가 남아 있어 {0}에 실행합니다."),
        ["rf.renewableShort"] = ("ready", "갱신 가능"),
        ["rf.notify.preTitle"] = ("{0}: renewable in {1} min", "{0}: {1}분 후 갱신 가능"),
        ["rf.notify.preBody"] = ("A new usage window can start at {0}.", "{0}부터 새 사용 주기를 시작할 수 있습니다."),
        ["rf.notify.readyTitle"] = ("{0}: renewable now", "{0}: 지금 갱신 가능"),
        ["rf.notify.readyBody"] = ("You can start a new usage window.", "새 사용 주기를 시작할 수 있습니다."),
        ["rf.notify.readyScheduled"] = ("Scheduled refresh will run at {0}.", "{0}에 예약 갱신이 실행됩니다."),
        // dialog
        ["rf.dlg.runTime"] = ("Run time", "실행 시간"),
        ["rf.dlg.atReset"] = ("As soon as renewable", "갱신 가능 즉시"),
        ["rf.dlg.atTime"] = ("At a set time", "시간 지정"),
        ["rf.dlg.afterReset"] = ("After renewable, delayed by", "갱신 가능 후"),
        ["rf.dlg.repeat"] = ("Repeat", "반복"),
        ["rf.dlg.once"] = ("Once", "한 번만"),
        ["rf.dlg.every"] = ("Every time it becomes renewable", "매 갱신 가능 시"),
        ["rf.dlg.window"] = ("Only within hours", "지정 시간대만"),
        ["rf.dlg.windowNote"] = ("No automatic requests outside these hours (e.g. overnight).", "이 시간대 밖(예: 새벽)에는 자동 요청을 보내지 않습니다."),
        ["rf.dlg.costMode"] = ("Run mode", "실행 방식"),
        ["rf.dlg.minimal"] = ("Minimal cost (cheapest model, low effort)", "최소 비용 (가장 저렴한 모델, 낮은 추론)"),
        ["rf.dlg.custom"] = ("Custom model", "사용자 지정 모델"),
        ["rf.dlg.request"] = ("Refresh request", "갱신 요청"),
        ["rf.dlg.defaultPrompt"] = ("Default minimal request (hi)", "기본 최소 요청 (hi)"),
        ["rf.dlg.customPrompt"] = ("Custom", "사용자 지정"),
        ["rf.dlg.preview"] = ("Renewable {0}   ·   Scheduled run {1}", "갱신 가능 {0}   ·   예약 실행 {1}"),
        ["rf.dlg.previewNone"] = ("Cannot plan: login required", "예약할 수 없음: 로그인 필요"),
        ["rf.dlg.schedule"] = ("Schedule", "예약"),
        ["rf.dlg.unschedule"] = ("Cancel schedule", "예약 취소"),
        ["rf.dlg.close"] = ("Close", "닫기"),
        ["rf.delay.min"] = ("+ {0} min", "+ {0}분"),
        ["rf.delay.hour"] = ("+ {0} h", "+ {0}시간"),
        ["rf.delay.hourMin"] = ("+ {0} h {1} min", "+ {0}시간 {1}분"),
        // settings
        ["rf.set.list"] = ("Schedules", "예약 목록"),
        ["rf.set.alerts"] = ("Alerts", "알림"),
        ["rf.set.alertOnReset"] = ("Renewable alert", "갱신 가능 알림"),
        ["rf.set.preNotify"] = ("Advance alert", "사전 알림"),
        ["rf.set.preOff"] = ("Off", "끄기"),
        ["rf.set.preMin"] = ("{0} min before", "{0}분 전"),
        ["rf.set.retry"] = ("Automatic retry", "자동 재시도"),
        ["rf.set.retryUse"] = ("Use", "사용"),
        ["rf.set.interval"] = ("Interval", "간격"),
        ["rf.set.max"] = ("Max", "최대"),
        ["rf.set.minutes"] = ("{0} min", "{0}분"),
        ["rf.set.times"] = ("{0} times", "{0}회"),
        ["rf.set.missed"] = ("If the scheduled time was missed (PC asleep)", "예약 시간을 놓친 경우 (PC 절전 등)"),
        ["rf.set.missed.RunOnWake"] = ("Run as soon as the PC wakes", "PC가 깨어난 즉시 실행"),
        ["rf.set.missed.WaitNext"] = ("Wait for the next time", "다음 갱신까지 대기"),
        ["rf.set.missed.Skip"] = ("Do not run", "실행하지 않음"),
        ["rf.set.missedNote"] = ("Even after waking, it runs only if a new window can start. The app must be running.", "깨어난 뒤에도 갱신 가능 여부를 다시 확인한 뒤 실행합니다. 앱이 실행 중이어야 합니다."),
        ["rf.set.log"] = ("Run log", "실행 로그"),
        ["rf.set.cli"] = ("CLI options used", "CLI 실행 옵션"),
        ["rf.set.cliText"] = ("Claude: claude -p --safe-mode --strict-mcp-config --tools \"\" --disable-slash-commands --no-session-persistence --effort low --model haiku < \"hi\"\nCodex: codex exec --ephemeral --ignore-user-config --skip-git-repo-check --sandbox read-only -C <empty folder> -c model_reasoning_effort=low - < \"hi\"",
            "Claude: claude -p --safe-mode --strict-mcp-config --tools \"\" --disable-slash-commands --no-session-persistence --effort low --model haiku < \"hi\"\nCodex: codex exec --ephemeral --ignore-user-config --skip-git-repo-check --sandbox read-only -C <빈 폴더> -c model_reasoning_effort=low - < \"hi\""),
        ["rf.set.noLog"] = ("No runs yet.", "아직 실행 기록이 없습니다."),
        ["rf.outcome.Success"] = ("Success", "성공"),
        ["rf.outcome.Failed"] = ("Failed", "실패"),
        ["rf.outcome.Postponed"] = ("Postponed", "보류"),
        ["rf.outcome.Missed"] = ("Missed", "놓침"),
        ["rf.outcome.Canceled"] = ("Canceled", "취소"),
        ["ui.login"] = ("Log in", "로그인"),
        ["ui.installCli"] = ("Install CLI", "CLI 설치"),
        ["ui.loginWaiting"] = ("Waiting for login…", "로그인 대기 중…"),
        ["pv.hint.login"] = ("Press the button to open the {0} login window.", "버튼을 누르면 {0} 로그인 창이 열립니다."),
        ["pv.hint.install"] = ("{0} CLI is not installed. After installing, the login window opens next.", "{0} CLI가 설치되어 있지 않습니다. 설치 후 로그인 창이 이어서 열립니다."),
        ["pv.hint.waiting"] = ("Finish logging in; it is detected automatically.", "로그인을 마치면 자동으로 감지합니다."),
        ["mv.installTitle"] = ("Install {0} CLI", "{0} CLI 설치"),
        ["mv.installBody"] = ("Install the {0} CLI?\n\nA PowerShell window will run:\n{1}\n\nThe login window opens when the install finishes.",
            "{0} CLI를 설치할까요?\n\nPowerShell 창에서 다음 명령을 실행합니다:\n{1}\n\n설치가 끝나면 로그인 창이 이어서 열립니다."),
        ["mv.nudgeTitle"] = ("{0}: login required", "{0} 로그인이 필요합니다"),
        ["mv.nudgeBody"] = ("Click to open the widget, then press Log in.", "클릭하면 위젯이 열립니다. [로그인] 버튼을 눌러 주세요."),
        ["mv.nudgeInstallBody"] = ("The CLI is not installed. Click to open the widget, then press Install CLI.", "CLI가 설치되어 있지 않습니다. 클릭하면 위젯이 열립니다. [CLI 설치] 버튼을 눌러 주세요."),
        ["mv.loginDetectedTitle"] = ("{0}: login detected", "{0} 로그인 확인됨"),
        ["mv.loginDetectedBody"] = ("Usage is now collected automatically.", "이제 사용량을 자동으로 수집합니다."),
        ["mv.installDetectedTitle"] = ("{0} CLI installed", "{0} CLI 설치 확인됨"),
        ["mv.installDetectedBody"] = ("Opening the login window.", "로그인 창을 엽니다."),
        ["mv.updateAvailableTitle"] = ("Update available: {0}", "새 버전 사용 가능: {0}"),
        ["mv.updateAvailableBody"] = ("Click to open Settings and download.", "클릭하면 설정에서 다운로드할 수 있습니다."),
        ["hint.claude"] = ("Run `claude` and sign in (/login)", "`claude` 실행 후 /login 으로 로그인하세요"),
        ["hint.codex"] = ("Run `codex login` with a ChatGPT account", "`codex login`으로 ChatGPT 계정에 로그인하세요"),
        ["hint.copilot"] = ("Run `copilot login` and sign in with GitHub", "`copilot login`으로 GitHub 계정에 로그인하세요"),

        // Main view model
        ["mv.subtitle"] = ("AI Coding Usage Control Center · chips, mini widget, dashboard", "AI 코딩 사용량 컨트롤 센터 · 칩, 미니 위젯, 대시보드"),
        ["mv.notifyTitle"] = ("{0}: {1} usage {2}%", "{0}: {1} 사용량 {2}%"),
        ["mv.notifyBody"] = ("Crossed {0}% · resets in {1} · source {2}", "{0}% 도달 · {1} 후 리셋 · 출처 {2}"),
        ["mv.refreshFailed"] = ("Refresh failed: {0}", "갱신 실패: {0}"),
        ["mv.historyHeader"] = ("time            provider account      5h   week  source", "시각            provider 계정          5시간 주간  출처"),
        ["mv.warn.Safe"] = ("Safe: local cache and manual snapshots only. No login files are read and no network requests are made.",
            "Safe: 로컬 캐시/수동 스냅샷만 사용합니다. 로그인 파일을 읽거나 네트워크 요청을 하지 않습니다."),
        ["mv.warn.Standard"] = ("Standard: reuses the Claude Code/Codex CLI login read-only to call the official usage lookup endpoints (no model calls, no usage consumed, tokens never refreshed or stored).",
            "Standard: Claude Code/Codex CLI 로그인을 읽기 전용으로 재사용해 공식 사용량 조회 엔드포인트만 호출합니다(모델 호출 아님, 사용량 소모 없음, 토큰 갱신/저장 안 함)."),
        ["mv.warn.Deep"] = ("Deep: Standard plus Codex session-log rate_limits fallback and WSL login discovery.",
            "Deep: Standard + Codex 세션 로그의 rate_limits fallback + WSL 로그인 탐색."),

        // Diagnostics
        ["dg.runtime"] = ("Runtime", "런타임"),
        ["dg.schema"] = ("State schema", "상태 스키마"),
        ["dg.mode"] = ("Mode", "모드"),
        ["dg.collection"] = ("Collection", "수집 레벨"),
        ["dg.collectionNote"] = ("(Safe < Standard < Deep; unverified collectors never run)", "(Safe < Standard < Deep, 검증 안 된 Collector는 실행 안 함)"),
        ["dg.wsl"] = ("WSL distros", "WSL 배포판"),
        ["dg.notDetected"] = ("Not detected", "감지 안 됨"),
        ["dg.disabled"] = ("(disabled)", "(사용 안 함)"),
        ["dg.health"] = ("Health", "상태"),
        ["dg.status"] = ("Status", "상세"),
        ["dg.configDir"] = ("Config dir", "설정 폴더"),
        ["dg.default"] = ("(default)", "(기본값)"),
        ["dg.lastOk"] = ("Last OK", "마지막 성공"),
        ["dg.last"] = ("last", "마지막 실행"),
        ["dg.verify"] = ("verify", "검증"),
        ["dg.fieldSources"] = ("Field sources", "필드별 출처"),
        ["dg.selected"] = ("Selected", "선택된 출처")
    };

    public static string Language { get; private set; } = "Korean";
    public static bool IsKorean => Language == "Korean";

    public static string T(string key, params object?[] args)
    {
        var format = Strings.TryGetValue(key, out var pair) ? (IsKorean ? pair.Ko : pair.En) : key;
        return args.Length == 0 ? format : string.Format(format, args);
    }

    // Returns the translation when the key exists, otherwise the raw value (for data such as source names).
    public static string Term(string prefix, string? value) =>
        value != null && Strings.ContainsKey(prefix + value) ? T(prefix + value) : value ?? "";

    public static string Msg(string key, params object?[] args) =>
        "@" + key + string.Concat(args.Select(a => Sep + (a?.ToString() ?? "")));

    public static string Display(string? stored)
    {
        if (string.IsNullOrEmpty(stored)) return "";
        if (stored[0] != '@') return stored;
        var parts = stored[1..].Split(Sep);
        // Arguments may themselves be message keys (e.g. a sign-in hint).
        return T(parts[0], parts.Skip(1).Select(p => (object?)Display(p)).ToArray());
    }

    public static void Apply(string language)
    {
        Language = language;
        var resources = System.Windows.Application.Current?.Resources;
        if (resources == null) return;
        // Every key is exposed so XAML can use any of them ({DynamicResource rf.title}, {DynamicResource ui.refresh}, ...).
        foreach (var key in Strings.Keys)
        {
            resources[key] = T(key);
        }
    }
}
